---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-crows-nest
  storagePolicy: cleartext
  labels:
    name: ucp-crows-nest
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.crows-nest
      dest:
        path: .source

data:
  chart_name: crows-nest
  release: ucp-crows-nest
  namespace: ucp
  wait:
    timeout: 600
    labels:
      release_group: airship-ucp-crows-nest
  test:
    enabled: true
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-ucp-crows-nest
  values: {}
  dependencies: []
